 version: '3.5'

 services:
   mysqldb:
     image: 'mysql:8'
     environment:
       - 'MYSQL_ROOT_PASSWORD=admin'
     networks:
       - sprnetw
     ports:
       - '3333:3306'
     volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - ./sql/data/compose/volumes:/var/lib/mysql
   springbootapp:
     container_name: app
     build:
       context: .
       dockerfile: Dockerfile
     image: mushiatsui/springbootapp
     environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb/warehouse
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_FLYWAY_URL=jdbc:mysql://mysqldb
      - SPRING_FLYWAY_USERNAME=root
      - SPRING_FLYWAY_PASSWORD=admin
     restart: on-failure
     depends_on:
       - mysqldb
     links:
       - mysqldb
     networks:
       - sprnetw
     ports:
       - 8080:8080
 networks:
   sprnetw:
     driver: bridge
 volumes:
  mysqldb:
    driver: local