FROM maven:3.6.3-openjdk-17 AS build
COPY backend/src /home/shopapp/src
#looking for swagger yaml in root folder
COPY backend/src/main/resources/swagger /src/main/resources/swagger
COPY backend/pom.xml /home/shopapp
RUN mvn -f /home/shopapp/pom.xml clean package

FROM openjdk:17-jdk-alpine
ARG JAR_FILE
COPY --from=build /home/shopapp/target/*.jar shopapp.jar
ENTRYPOINT ["java","-jar","/shopapp.jar"]