apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.warehouseapp.fullname }}-configmap
  namespace: {{ .Values.warehouseapp.namespace }}
data:
  DB_URL: jdbc:mysql://{{ .Values.warehousedatabase.fullname}}-service.{{ .Values.warehousedatabase.namespace}}/{{ .Values.warehouseapp.data.schema}}
  DB_USERNAME: {{ .Values.warehouseapp.data.dbUsername}}
  FLYWAY_DB_URL: jdbc:mysql://{{ .Values.warehousedatabase.fullname}}-service.{{ .Values.warehousedatabase.namespace}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.warehouseapp.fullname }}-secret
  namespace: {{ .Values.warehouseapp.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=