apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.warehouseapp.fullname }}
  namespace: {{ .Values.warehouseapp.namespace }}
spec:
  replicas: {{ .Values.warehouseapp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.warehouseapp.fullname }}
  template:
    metadata:
      labels:
        app: {{ .Values.warehouseapp.fullname }}
    spec:
      containers:
        - name: {{ .Values.warehouseapp.fullname }}
          image: mushiatsui/springbootapp
          #        resources:
          #          limits:
          #            memory: "4000M"
          #            cpu: "1000m"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.warehouseapp.fullname }}-configmap
                  key: DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.warehouseapp.fullname }}-configmap
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  # name -> metadata name of the secret
                  name: {{ .Values.warehouseapp.fullname }}-secret
                  # name of the secret data
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_FLYWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.warehouseapp.fullname }}-configmap
                  key: FLYWAY_DB_URL
            - name: SPRING_FLYWAY_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.warehouseapp.fullname }}-configmap
                  key: DB_USERNAME
            - name: SPRING_FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  # name -> metadata name of the secret
                  name: {{ .Values.warehouseapp.fullname }}-secret
                  # name of the secret data
                  key: MYSQL_ROOT_PASSWORD