apiVersion: v1
kind: Service
metadata:
  # name of the service
  name: {{ .Values.warehouseapp.fullname }}
  namespace: {{ .Values.warehouseapp.namespace }}
spec:
  selector:
    app: {{ .Values.warehouseapp.fullname }}
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30000