apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume
  labels:
    type: local
spec:
  storageClassName: database-storage-class
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/databaseVolume/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
  namespace: database
spec:
  storageClassName: database-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi