spring:
    jpa:
    # temp
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    datasource:
        url: jdbc:mysql://127.0.0.1:3333/warehouse
        username: root
        password: admin
    flyway:
        url: jdbc:mysql://127.0.0.1:3333
        user: root
        password: admin
        default-schema: warehouse
        create-schemas: true
app-config:
    cache:
        clear-cache:
            fixed-timer: "0 0/1 * * * *"