spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3333/warehouse
        username: root
        password: admin
    flyway:
        url: jdbc:mysql://127.0.0.1:3333
        user: root
        password: admin
        default-schema: warehouse
        create-schemas: true
