spring:

#    database configs
    jpa:
        hibernate:
            ddl-auto: none
    # for testing
        # show-sql: true
        # properties:
        #     hibernate:
        #         format_sql: true
    datasource:
        url: jdbc:mysql://127.0.0.1:3333/warehouse
        username: root
        password: admin

#    db migration configs
    flyway:
        url: jdbc:mysql://127.0.0.1:3333
        user: root
        password: admin
        schemas: warehouse
        create-schemas: true
        baseline-on-migrate: true

#        rabbitmq configs
    rabbitmq:
        template:
            queue:
                productCountChange: productQuantityChange_queue
                sendOrder: sendOrder_queue
            exchange: exchange
            routing-key:
                productCountChange: productQuantityChange_routingKey
                sendOrder: sendOrder_routingKey
#LOCAL SETTING
        host: localhost
        port: 5672
        username: user
        password: user

    #Security Keycloak
    security:
      oauth2:
        resource-server:
          jwt:
              issuer-uri: http://localhost:9090/realms/ProjectRealm
#custom configs
app-config:
    cache:
        clear-cache:
            # for testing
            # fixed-timer: "0 0/1 * * * *"
            fixed-timer: "0 0 0/24 * * *"