server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: none

#   for testing
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
    template:
      queue:
        sendOrderQueue: sendOrder_queue
#      default-receive-queue: sendOrder_queue

  datasource:
    url: jdbc:mysql://127.0.0.1:3333/orders
    username: root
    password: admin

  flyway:
    url: jdbc:mysql://127.0.0.1:3333
    user: root
    password: admin
    schemas: orders
    create-schemas: true
    baseline-on-migrate: true
