version: '3.5'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
#      Docker connects to other services inside by its own IP (host.docker.internal) or by Service name if ine the same network
      KC_DB_URL: jdbc:mysql://host.docker.internal:3333/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - start-dev