apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secret
  namespace: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secret
  namespace: warehouse-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=
